name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.2.0
      - name: Install poetry-dynamic-versioning
        run: pip install poetry-dynamic-versioning
      - name: Poetry - Cache
        id: poetry-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Poetry - Install
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install
      - name: Poetry - Build
        run: poetry build
      - name: Poetry - Publish
        run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
